# .github/workflows/update-images.yml

name: Update Image URLs

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # As per previous updates

      - name: Install Dependencies
        run: npm install

      - name: Fetch Image URLs
        run: node scripts/fetchImageUrls.js

      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add images.json
          git commit -m "Update image URLs [skip ci]" || echo "No changes to commit"
          git push
